<?php
include 'includes/path.php';
include 'includes/admin-header.php';
?>
<?php echo $directory; ?>
<section>
  <div class="container">
    <div class="row mt-2 pb-3">
      <div class="col-sm-12 col-md-12 col-lg-12 mb-2">
        <div class="card">
          <i class="fas fa-plus" class="card-img-top"></i>
          <div class="card-body">
            <h5 class="card-title">Item Add Form</h5>
            <p class="card-text">Add Item Details</p>
          </div>
          <div class="card-body">
            <form method="post" action="<?php echo $directory; ?>/Controllers/item_Controller.php" enctype="multipart/form-data">
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="name">Item Name</label>
                  <input type="text" name="name" class="form-control" id="name" placeholder="Enter Item Name">
                </div>
                <div class="form-group col-md-6">
                  <label for="price">Item Description</label>
                  <input type="text" name="description" class="form-control" id="description" placeholder="Enter Item Description">
                </div>
                <div class="form-group col-md-6">
                  <label for="price">Item Price</label>
                  <input type="number" name="price" class="form-control" id="price" placeholder="Enter Produt Price">
                </div>
              </div>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <label for="code">Item Unique Code</label>
                  <input type="number" name="code" class="form-control" id="code" placeholder="Enter Prodcut Code">
                </div>
              </div>
              <div class="form-group">
                <div class="custom-file">
                  <input type="file" name="file" class="custom-file-input" id="file">
                  <label class="custom-file-label" for="file">Choose file</label>
                </div>
              </div>
              <button type="submit" name="submit" id="submit" class="btn btn-primary">Add Item</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

  </div>
  <script type="text/javascript" src="js/index.js"></script>
  <?php
  include 'includes/footer.php';