<?php
include 'includes/header.php';
?>
<div class="jumbotron jumbotron-fluid bg-primary">
  <div class="container">
    <h1 class="display-4 text-white font-weight-bold">Admin Login Form </h1>
    <p class="lead text-white font-weight-bold">Kindly Login to Add/View Products.</p>
  </div>
</div>
<section>
  <div class="card">
  <div class="card-body">
    <div class="container">
       <div class="row">
         <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
           <div class="card border-0 shadow rounded-3 my-5">
             <div class="card-body p-4 p-sm-5">
               <h5 class="card-title text-center mb-5 fw-light fs-5">Login In</h5>
               <form method="post" action="admin-login-action.php">
                 <div class="form-floating mb-3">
                   <input type="email" class="form-control" id="email" name="email" placeholder="Enter your Email address">
                   <label for="email">Email address</label>
                 </div>
                 <div class="form-floating mb-3">
                   <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                   <label for="password">Password</label>
                 </div>

                 <div class="d-grid text-center">
                   <button class="btn btn-primary btn-login text-uppercase text-center fw-bold" name="submit" type="submit">Sign
                     in</button>
                 </div>
                 <hr class="my-4">
               </form>
             </div>
           </div>
         </div>
       </div>
     </div>
  </div>
</div>
</section>
  </div>
<script type="text/javascript" src="js/index.js"></script>
<script type="text/javascript">
  document.getElementById("main-jumbotron").style.display = "none";
</script>
<?php
include 'includes/footer.php';