<?php
include 'includes/header.php';
include 'includes/navbar.php';
// include 'includes/navbar.php';
?>

<section>
  <div class="card">
  <div class="card-body">
    <div class="container">
       <div class="row">
         <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
           <div class="card border-0 shadow rounded-3 my-5">
             <div class="card-body p-4 p-sm-5">
               <h5 class="card-title text-center mb-5 fw-light fs-1 text-success"><b>Registration</b></h5>
               <form method="post" action="<?php echo $directory; ?>/Controllers/register_Controller.php">
                 <div class="form-floating mb-3">
                   <input type="email" class="form-control" id="email" name="email" placeholder="Enter your Email address">
                   <label for="email">Email </label>
                 </div>
                 <div class="form-floating mb-3">
                   <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                   <label for="password">Password</label>
                 </div>

                 <div class="d-grid text-center">
                   <button class="btn btn-secondary btn-login text-uppercase text-center fw-bold" name="submit" type="submit">Confirm</button>
                 </div>
                 <hr class="my-4">
               </form>
             </div>
           </div>
         </div>
       </div>
     </div>
  </div>
</div>
</section>
  </div>
<script type="text/javascript" src="js/index.js"></script>
<script type="text/javascript">
  document.getElementById("main-jumbotron").style.display = "none";
</script>
<?php
include 'includes/footer.php';